# Generated by Django 4.2.13 on 2024-06-17 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_singer'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sub',
            field=models.CharField(blank=True, max_length=1000000, null=True),
        ),
    ]
