# Generated by Django 4.2.13 on 2024-06-18 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_sub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='sub',
            field=models.TextField(blank=True, max_length=1000000, null=True),
        ),
    ]
