# Generated by Django 4.2.13 on 2024-06-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_account_created_alter_account_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='age',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
