# Generated by Django 4.2.13 on 2024-06-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_account_age_account_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='birth',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(default='', max_length=11),
        ),
    ]
