# Generated by Django 4.2.13 on 2024-06-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_tags_alter_post_singer_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grouping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=20)),
                ('posts', models.ManyToManyField(blank=True, null=True, to='blog.post')),
            ],
        ),
    ]
