# Generated by Django 4.2.13 on 2024-06-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='group_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Grouping',
        ),
    ]
