# Generated by Django 4.2.13 on 2024-06-24 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_category_remove_post_group_name_post_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Category_name',
            new_name='Category_Name',
        ),
    ]
